#!/bin/bash

# Define the folder for output files
OUTPUT_FOLDER="outputs"

# Create the folder if it doesn't exist
mkdir -p $OUTPUT_FOLDER

# Redirect each command's output to a unique .txt file inside the folder
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/prom/prom_300_all -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {1} --handle_n_setting {remove} --ratio_pretrain_train {0.0} > $OUTPUT_FOLDER/output_prom_300_all.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/prom/prom_300_all -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {1} --handle_n_setting {remove} --ratio_pretrain_train {0.0} > $OUTPUT_FOLDER/output_prom_300_all.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/prom/prom_core_tata -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {5.0} --nb_train_iterations {3} --handle_n_setting {remove} --ratio_pretrain_train {0.0} > $OUTPUT_FOLDER/output_prom_core_tata.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/prom/prom_core_tata -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {5.0} --nb_train_iterations {3} --handle_n_setting {remove} --ratio_pretrain_train {0.0} > $OUTPUT_FOLDER/output_prom_core_tata.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/prom/prom_core_notata -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {3} --handle_n_setting {remove} --ratio_pretrain_train {0.01} > $OUTPUT_FOLDER/output_prom_core_notata.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/prom/prom_core_notata -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {3} --handle_n_setting {remove} --ratio_pretrain_train {0.01} > $OUTPUT_FOLDER/output_prom_core_notata.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/tf/4 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {3.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.25} > $OUTPUT_FOLDER/output_tf4.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/tf/4 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {3.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.25} > $OUTPUT_FOLDER/output_tf4.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H3 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {3.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.25} > $OUTPUT_FOLDER/output_EMP_H3.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H3 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {3.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.25} > $OUTPUT_FOLDER/output_EMP_H3.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/splice/reconstructed -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {3.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_splice.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/splice/reconstructed -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {3.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_splice.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/tf/2 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {5.0} --nb_train_iterations {1} --handle_n_setting {remove} --ratio_pretrain_train {0.25} > $OUTPUT_FOLDER/output_tf2.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/tf/2 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {5.0} --nb_train_iterations {1} --handle_n_setting {remove} --ratio_pretrain_train {0.25} > $OUTPUT_FOLDER/output_tf2.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H4 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.0} > $OUTPUT_FOLDER/output_EMP_H4.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H4 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.0} > $OUTPUT_FOLDER/output_EMP_H4.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/tf/3 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {7} --handle_n_setting {remove} --ratio_pretrain_train {0.25} > $OUTPUT_FOLDER/output_tf3.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/tf/3 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {7} --handle_n_setting {remove} --ratio_pretrain_train {0.25} > $OUTPUT_FOLDER/output_tf3.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H4ac -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {0.75} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.01} > $OUTPUT_FOLDER/output_EMP_H4ac.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H4ac -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {0.75} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.01} > $OUTPUT_FOLDER/output_EMP_H4ac.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/tf/1 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {3.0} --nb_train_iterations {7} --handle_n_setting {remove} --ratio_pretrain_train {0.01} > $OUTPUT_FOLDER/output_tf1.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/tf/1 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {3.0} --nb_train_iterations {7} --handle_n_setting {remove} --ratio_pretrain_train {0.01} > $OUTPUT_FOLDER/output_tf1.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/prom/prom_300_tata -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {5} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_prom_300_tata.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/prom/prom_300_tata -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {5} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_prom_300_tata.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/tf/0 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {5.0} --nb_train_iterations {5} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_tf0.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/tf/0 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {5.0} --nb_train_iterations {5} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_tf0.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H3K36me3 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {1.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.0} > $OUTPUT_FOLDER/output_EMP_H3K36me3.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H3K36me3 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {1.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.0} > $OUTPUT_FOLDER/output_EMP_H3K36me3.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/mouse/4 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {5.0} --nb_train_iterations {5} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_mouse4.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/mouse/4 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {5.0} --nb_train_iterations {5} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_mouse4.txt 2>&1 &
# echo "python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/mouse/1 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {3} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_mouse1.txt 2>&1 &"
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/mouse/1 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {3} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_mouse1.txt 2>&1 &
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H3K14ac -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {1.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.25} > $OUTPUT_FOLDER/output_EMP_H3K14ac.txt 2>&1
#python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/mouse/0 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {5.0} --nb_train_iterations {7} --handle_n_setting {remove} --ratio_pretrain_train {0.25} > $OUTPUT_FOLDER/output_mouse0.txt 2>&1
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/mouse/2 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {3.0} --nb_train_iterations {7} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_mouse2.txt 2>&1
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/mouse/3 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {5.0} --nb_train_iterations {3} --handle_n_setting {remove} --ratio_pretrain_train {0.01} > $OUTPUT_FOLDER/output_mouse3.txt 2>&1
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/prom/prom_300_notata -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {1} --handle_n_setting {remove} --ratio_pretrain_train {0.0} > $OUTPUT_FOLDER/output_prom_300_notata.txt 2>&1
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H3K4me2 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {1.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.25} > $OUTPUT_FOLDER/output_EMP_H3K4me2.txt 2>&1
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H3K4me3 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {1.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.0} > $OUTPUT_FOLDER/output_EMP_H3K4me3.txt 2>&1
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H3K4me1 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {0.75} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.25} > $OUTPUT_FOLDER/output_EMP_H3K4me1.txt 2>&1
python make_covid_spa.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/virus/covid -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {False} --gamma {0.1} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.0} > $OUTPUT_FOLDER/output_covid.txt 2>&1
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H3K79me3 -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {1.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_EMP_H3K79me3.txt 2>&1
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/prom/prom_core_all -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {5.0} --nb_train_iterations {1} --handle_n_setting {remove} --ratio_pretrain_train {0.01} > $OUTPUT_FOLDER/output_prom_core_all.txt 2>&1
# python explore.py -dataset_folder /Users/eugenemin/Documents/genomics_classification/GUE/EMP/H3K9ac -pretrain_file /Users/eugenemin/Documents/genomics_classification/dnabert_2_pretrain/dev.txt --include_prev_context {True} --gamma {1.0} --nb_train_iterations {10} --handle_n_setting {remove} --ratio_pretrain_train {0.1} > $OUTPUT_FOLDER/output_EMP_H3K9ac.txt 2>&1

# Notify the user
echo "All commands executed. Outputs are stored in the folder '$OUTPUT_FOLDER'."
